// C'est donnée ne sonnt pas la version finale

export const peuples = [
  {
    id: 1,
    nom: "Les Mécanistes",
    description: "Inventeurs steampunk maîtrisant vapeur, engrenages et dirigeables",
    zone: "La Cité des Engrenages",
    zoneId: 1,
    caracteristiques: [
      "Maîtrise de la vapeur",
      "Création d'engrenages",
      "Construction de dirigeables",
      "Innovation technologique",
    ],
    competences: ["ingénierie", "mécanique", "invention", "navigation aérienne"],
    style: "steampunk",
    couleurs: ["cuivre", "bronze", "gris métallique"],
  },
  {
    id: 2,
    nom: "Les Sylvans",
    description: "Gardiens féeriques de la forêt enchantée",
    zone: "Sylva Enchantée",
    zoneId: 2,
    caracteristiques: [
      "Communion avec la nature",
      "Magie naturelle",
      "Protection de la forêt",
      "Communication avec les esprits",
    ],
    competences: ["magie naturelle", "guérison", "communication animale", "botanique magique"],
    style: "féerique",
    couleurs: ["vert émeraude", "or", "violet mystique"],
  },
  {
    id: 3,
    nom: "Les Aetheriens",
    description: "Voyageurs du ciel et protecteurs des îles flottantes",
    zone: "Aetherium Ascendant",
    zoneId: 3,
    caracteristiques: ["Maîtrise du vol", "Protection des îles", "Navigation céleste", "Gardiens de l'Aetherion"],
    competences: ["vol", "navigation aérienne", "manipulation de l'Aetherion", "défense céleste"],
    style: "céleste",
    couleurs: ["doré", "blanc", "bleu azur"],
  },
  {
    id: 4,
    nom: "Les Néxiens",
    description: "Habitants d'une dimension alternative instable, le Nexus Obscura",
    zone: "Nexus Obscura",
    zoneId: 4,
    caracteristiques: [
      "Adaptation dimensionnelle",
      "Manipulation de l'espace-temps",
      "Résistance à l'instabilité",
      "Connaissance des paradoxes",
    ],
    competences: ["voyage dimensionnel", "illusions", "manipulation temporelle", "perception altérée"],
    style: "mystique",
    couleurs: ["noir", "violet sombre", "argent"],
  },
];
